globals:
  __PATH_PREFIX__: true
env:
  browser: true
  es2021: true
extends:
  - airbnb
  - plugin:import/typescript
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 13
  sourceType: module
  allowImportEverywhere: true
plugins:
  - '@typescript-eslint'
  - prettier
overrides:
  - files: '*.mdx'
    extends: 'plugin:mdx/recommended'
    globals:
      props: true
      Toc: true
      Caption: true
    rules:
      'react/prop-types': off
      'react/jsx-filename-extension': off
      'import/prefer-default-export': off
  - files: '*.(t|j)sx?'
  - files: 'types/graphql-types.ts'
    rules:
      quotes: off
rules:
  quotes:
    - error
    - backtick
  'prettier/prettier': error
  'react/jsx-filename-extension':
    - error
    - allow: 'as-needed'
      extensions:
        - .jsx
        - .tsx
  'react/jsx-props-no-spreading': off
  'react/require-default-props': off
  'import/extensions':
    - error
    - never
    - extensions:
      css: 'always'
      scss: 'always'
  'import/no-extraneous-dependencies':
    - error
    - devDependencies:
        - '**/*.spec.js'
        - '**/*.spec.ts'
        - '**/*.spec.jsx'
        - '**/*.spec.tsx'
        - '**/__test__/*'
        - '**/__mocks__/*'
        - './webpack.config.ts'
        - 'eslint_rules/*'
  no-use-before-define: off
  '@typescript-eslint/no-use-before-define':
    - error
  no-unused-vars: off
  '@typescript-eslint/no-unused-vars':
    - error
    - varsIgnorePattern: ^_
      argsIgnorePattern: ^_
  no-shadow: off
  '@typescript-eslint/no-shadow':
    - error
  'react/function-component-definition':
    - error
    - namedComponents: arrow-function
      unnamedComponents: arrow-function
  'react/static-property-placement':
    - error
    - static public field
