name: Continuous Integration
'on':
  push:
    branches:
      - main
      - staging
      - trying
jobs:
  node-ci:
    name: Build Gatsby Site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Build Cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: "${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}"
          restore-keys: "${{ runner.os }}-node-\n"
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn lint
      - name: Build Site
        run: yarn build
      # - name: Test
      #   run: yarn test
      # - name: Upload Codecov
      #   uses: codecov/codecov-action@v2
      #   with:
      #     token: '${{ secrets.CODECOV_TOKEN }}'
      #     files: coverage/coverage-final.json
      #     flags: ui
      #     fail_ci_if_error: true
      #     verbose: true
